export enum ErrorCode {
    MISSING_API_KEY = 'MISSING_API_KEY',
    INVALID_API_KEY = 'INVALID_API_KEY',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    NO_MESSAGE_EXTRACTED = 'NO_MESSAGE_EXTRACTED',
    LANGUAGE_DETECTION_FAILED = 'LANGUAGE_DETECTION_FAILED',
    SCAM_CLASSIFICATION_FAILED = 'SCAM_CLASSIFICATION_FAILED',
    IMAGE_DOWNLOAD_FAILED = 'IMAGE_DOWNLOAD_FAILED',
    OCR_FAILED = 'OCR_FAILED',
}

export interface ErrorPayload {
    message: string;
    code: ErrorCode;
    metadata?: Record<string, any>;
}
